# -*- coding: utf-8 -*-
"""webscraping_novelfull.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VaslwXHXule1zXQmeZ3tmrfJ1MflXBfd
"""



import requests
from bs4 import BeautifulSoup
baseurl='https://novelfull.com'
url=requests.get('https://novelfull.com/')
soup=BeautifulSoup(url.content, 'html')
product_list=soup.find_all('div', class_='index-intro')
productlinks=[]

for item in product_list:
  for link in item.find_all('a', href=True):
    productlinks.append(baseurl+link['href']) 
for links in productlinks:
  r=requests.get(links)
  soup=BeautifulSoup(r.content, 'html')
  name=soup.find('h3', class_='title')
  if name is not None:
    titles = name.text
  else:
    titles = None

  print(titles)